name: Crosspost Action
description: "Automatically submits URLs to variety of social networks like: Bluesky, Mastodon, Twitter, LinedIn, Discord, Telgram, Dev.to."
inputs:
  sitemap-url:
    description: URL to sitemap.xml
    required: true
  since:
    description: Post only items newer than this (e.g. '1' 'since-unit' ago)
    required: false
    default: '1'
  since-unit:
    description: Unit for 'since' input (e.g. minute, hour, day, week, month, year)
    required: false
    default: day
  limit:
    description: Maximum number of items to post
    required: false
    default: '100'
  failure-strategy:
    description: "Define how to handle failures. Options: ignore, error."
    required: false
    default: ignore
  lastmod-required:
    description: "Define the behavior when lastmod tag is not present in sitemap. Options: ignore, error."
    required: false
    default: error

  message:
    description: Message to include with the post (use {url} as placeholder for the URL)
    required: false
    default: "New blog post: {url}"

  # Twitter
  twitter_access_token_key:
    description: Twitter Access Token Key
    required: false
    default: ''
  twitter_access_token_secret:
    description: Twitter Access Token Secret
    required: false
    default: ''
  twitter_api_consumer_key:
    description: Twitter API Consumer Key
    required: false
    default: ''
  twitter_api_consumer_secret:
    description: Twitter API Consumer Secret
    required: false
    default: ''

  # Mastodon
  mastodon_access_token:
    description: Mastodon Access Token
    required: false
    default: ''
  mastodon_host:
    description: Mastodon Host (e.g. mastodon.social)
    required: false
    default: ''

  # Bluesky
  bluesky_host:
    description: Bluesky Host (e.g. bsky.social)
    required: false
    default: ''
  bluesky_identifier:
    description: Bluesky Identifier (e.g. user.bsky.social)
    required: false
    default: ''
  bluesky_password:
    description: Bluesky Password for the account
    required: false
    default: ''

  # LinkedIn
  linkedin_access_token:
    description: LinkedIn Access Token
    required: false
    default: ''

  # Discord
  discord_bot_token:
    description: Discord Bot Token
    required: false
    default: ''
  discord_channel_id:
    description: Discord Channel ID
    required: false
    default: ''

  # Discord Webhook
  discord_webhook_url:
    description: Discord Webhook URL
    required: false
    default: ''

  # Dev.to
  devto_api_key:
    description: dev.to API Key
    required: false
    default: ''

  # Telegram
  telegram_bot_token:
    description: Telegram Bot Token
    required: false
    default: ''
  telegram_chat_id:
    description: Telegram Chat ID
    required: false
    default: ''

  # Slack
  slack_token:
    description: Slack Token
    required: false
    default: ''
  slack_channel:
    description: Slack Channel
    required: false
    default: ''

  # # General Crosspost .env
  # crosspost_detenv_file:
  #   description: Crosspost .env file path
  #   required: false
  #   default: .env

outputs:
  latest-urls:
    description: Latest URLs found in sitemap
    value: ${{ steps.get-urls.outputs.latest-urls }}
  posted-urls:
    description: Posted URLs
    value: ${{ steps.post-urls.outputs.posted-urls }}
runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@v5
      with:
        node-version-file: package.json
        cache: npm

    - name: Install dependencies
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        set -x
        sudo apt-get update && sudo apt-get install -y jq xmlstarlet
        npm ci

    - name: Get URLs from Sitemap
      shell: bash
      id: get-urls
      run: |
        SITEMAP_URL="${{ inputs.sitemap-url }}"

        # Get current time and since requested ago in ISO 8601
        NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        SINCE_AGO=$(date -u -d '${{ input.since }} ${{ input.since-unit }} ago' +"%Y-%m-%dT%H:%M:%SZ")

        # Fetch and parse sitemap, get URLs with lastmod since SINCE_AGO
        UPDATED_URLS=$(curl -s "$SITEMAP_URL" | \
          xmlstarlet sel -N x="http://www.sitemaps.org/schemas/sitemap/0.9" \
            -t -m "//x:url" \
            -v "x:loc" -o "|" -v "x:lastmod" -n | \
          while IFS="|" read -r url lastmod; do
            # Convert lastmod to UTC ISO 8601 (Z)
            lastmod_iso=$(date -u -d "$lastmod" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")
            # If lastmod is empty or conversion failed, skip
            if [[ -z "$lastmod_iso" ]]; then
              continue
            fi
            # Compare lastmod to SINCE_AGO
            if [[ "$lastmod_iso" > "$SINCE_AGO" ]]; then
              echo "$url"
            fi
          done | sort -u)

        if [[ -z "$UPDATED_URLS" ]]; then
          echo "No URLs updated in the ${{ input.since }} ${{ input.since-unit }}."
          exit 0
        fi

        # Iterate over each updated URL and notify all search engines
        echo "$UPDATED_URLS" | while read -r url; do
          echo "Processing URL: $url"
        done

        echo "latest-urls=$UPDATED_URLS" >> $GITHUB_OUTPUT

    - name: Post URLs
      id: post-urls
      shell: bash
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      run: |
        set -x
        npx crosspost --version
        echo "posted-urls=$INPUT_URL" >> $GITHUB_OUTPUT
