name: Build & Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
    branches:
      - main
      # - feature/*
      # - bugfix/*
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Guess next version
      id: guessed_tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        append_to_pre_release_tag: pre
    - name: Extract version from tag
      env:
        VERSION_TAG: ${{ steps.guessed_tag_version.outputs.new_tag }}
      run: echo "VERSION=$(echo $VERSION_TAG | sed -e "s/^v//" -e "s/-.*$//")" >> $GITHUB_ENV

  smoke-test:
    name: smoke test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64 # Windows ARM64 is a niche
    needs: build
    steps:
    - name: Run action-crosspost on a test sitemap
      uses: tgagor/action-crosspost@${{ github.sha }}
      with:
        dry-run: true
        feed-url: https://gagor.pro/sitemap.xml
        since: '1'
        since-unit: year
        mastodon-access-token: its-dry-run-so-whatever
        mastodon-host: mastodon.social
        exclude-urls: |
          https://gagor.pro/
          https://gagor.pro/author*
          https://gagor.pro/tags/*
          https://gagor.pro/categories/*
          https://gagor.pro/posts/*
          https://gagor.pro/about/
        filter-urls: |
          20

  pre-commit:
    name: pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pre-commit/action@v3.0.1

  release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - build
      - smoke-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract version from tag on master
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create normal GitHub release
        if: github.ref == 'refs/heads/main' && github.event_name != 'schedule'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Move major version tag
        run: |
          # Find tag (vX.Y.Z) that points to this commit
          VERSION_TAG=$(git tag --points-at HEAD | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)

          if [ -z "$VERSION_TAG" ]; then
            echo "No version tag found on this commit, skipping."
            exit 0
          fi

          echo "Found version tag: $VERSION_TAG"

          VERSION="${VERSION_TAG#v}"      # e.g. 1.2.3
          MAJOR="${VERSION%%.*}"          # e.g. 1

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag -f "v$MAJOR"
          git push origin "v$MAJOR" --force

  dependabot:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - build
      - smoke-test
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --squash --auto "$PR_URL"
